Repository AdamOswald/tes, pull requests merged in 2022-11, with the labels that each got.

#30 S
  online-band-master/.snyk
  online-band-master/package.json
Labels: :mag: Ready for Review, Small

#31 S
  .github/dependabot.yml
  PyDaw-0.4.6/daw/dummy.py
  PyDaw-0.4.6/daw/exceptions.py
  PyDaw-0.4.6/daw/lmms.py
  PyDaw-0.4.6/test.py
  music-theme-recognition-main/building_model/model.py
  music-theme-recognition-main/building_model/mtr_utils/config.py
  music-theme-recognition-main/building_model/mtr_utils/export_results.py
  music-theme-recognition-main/building_model/mtr_utils/feature_selection/auto_feature_selection.py
  music-theme-recognition-main/building_model/mtr_utils/feature_selection/load_feature_set.py
  music-theme-recognition-main/building_model/mtr_utils/scoring.py
  music-theme-recognition-main/calculating_dataset/definition_dump.py
  music-theme-recognition-main/calculating_dataset/generate_jsymbolic_config.py
  music-theme-recognition-main/collecting_data/1_scraping_midi/scrape_bitmidi.py
  music-theme-recognition-main/collecting_data/1_scraping_midi/scrape_freemidi.py
  music-theme-recognition-main/collecting_data/1_scraping_midi/scrape_midiworld.py
  music-theme-recognition-main/collecting_data/2_building_dataset/db_stats.py
  music-theme-recognition-main/evaluating_results/eval_utils/config.py
  music-theme-recognition-main/evaluating_results/eval_utils/export_eval.py
  music-theme-recognition-main/evaluating_results/eval_utils/results_stats_utils.py
  music-theme-recognition-main/evaluating_results/feature_importances.py
  music-theme-recognition-main/evaluating_results/graph.py
  music-theme-recognition-main/evaluating_results/plot_trees.py
  music-theme-recognition-main/evaluating_results/results_stats.py
  setup.py
Labels: :mag: Ready for Review, Large

#33 S
  audiolm-pytorch-main/audiolm.png
  leitmotif-master/fonts/bravura/Bravura.svg
  music-theme-recognition-main/data/labels/label_freq.png
  music-theme-recognition-main/data/labels/theme_label_frequencies.png
  project-adam-master/Adam Ive.png
Labels: :mag: Ready for Review, No Changes
